### ISSUE TITLE
Ревью кода

### ISSUE THREAD

**Issue by S1x6** [S1x6/Huffman#1]
@avkomar

**Comment by avkomar** [comment]
@S1x6 
По существу серьезных замечаний по код нет.
Замечания общего характера:
1. Не нужно в git-репозиторий выкладывать служебные файлы проекта. Нужны только исходники: файлы `.c` и `.h` + возможно файл проекта `.vcprojx`.
2. Если `copyFile` так и не был написан, то нужно удалить все ссылки на него
3. Память выделенную `malloc` нужно стараться освободить сразу как только она не нужна.
4. По документированию функций:
  * описание функции должно быть максимально однозначным и не допускать двоякого толкования
  * по каждому аргументу, по имени
    * тип (возможные принимаемые значения, например только `0` и `1`) 
    * семантика, т.е. как функция его интерпретирует
    * кто проверяет значения на валидность. Может быть единообразное соглашение, что все проверки, например, делает `caller`, тогда этого можно не писать
  * как нужно интрепретировать возвращаемое `return`-ом значение
   Лучше если задокументировано формально с поддержкой синтаксиса по авто-генерации документации для исходного кода. Например, [doxygen](http://www.stack.nl/~dimitri/doxygen/). Вот, простая [вводная статья](https://habrahabr.ru/post/252101/).

Например описание: 
> int countTreeBits(Tree * tree); //считает количество бит на запись дерева

вводит в заблуждение, так как в реальности функция возращает не всю длину дерева, а `n%8`, где `n`-число вершин в дереве.

Ниже пример более "приличной" документации на эту функцию
```
/**
 * \brief функция считает остаток от деления на 8 длины битовой записи дерева Хаффмана.
 * 
 * \param [in] tree ненулевой указатель на корень дерева
 * 
 * \return целое от 0 до 7, равное n%8, где n -число вершин в дереве
 **/
int countTreeBits(Tree * tree);
```

Больше замечаний нет. Задача принята.

**Comment by avkomar** [comment]
@S1x6 
можете закрывать issue.
только сделайте cleanup в репозитории: удалите папки `x64` и `.vs`
